### ISSUE TITLE
Estimar parâmetros e condições iniciais. Documentar Fontes dos Parametros

### ISSUE THREAD

**Issue by dsevero** [3778/COVID-19#2]
- [x] Levantamento dos coeficientes (ex: % de casos assintomáticos, tempo de duração da doença, tempo de infecciosidade, etc)

- [x] Quantidade de infectados e recuperados (condições iniciais S0, E0, I0 e R0).

**Comment by Mauroncard** [comment]
"The median duration to negative reverse-transcriptase PCR tests of upper respiratory tract samples was **11 days (95 CIs: 10-12 days)**."

o que sugere um γ (gamma) de 11 ^-1
