### ISSUE TITLE
Epidemic Calculator

### ISSUE THREAD

**Issue by melffagundes** [3778/COVID-19#39]
Oi, Pessoal.
Não sei se já conhecem o modelo usado pelo Gabriel Goh http://gabgoh.github.io/COVID/index.html

**Comment by dsevero** [comment]
Esse modelo é muito legal mesmo! Usei inicialmente pra ver se implementei certo o SEIR-Bayes. 

É similar ao nosso SEIR-Bayes. A única diferença é que o deles inclui um slider pra intervenção pública, e 3 compartimentos ligados ao nosso R (porem, as equações diferenciais aso as mesmas ate onde vi logo a dinâmica não muda).

A vantagem do nosso é que os parâmetros (i.e. R0, tempo de incubação e recuperação) não são deterministicos, mas sim uma distribuição lognormal com média de desvio padrão. Isso permite capturar melhor as incertezas presentes na literatura e nos [parâmetros que estamos estimando](https://github.com/3778/COVID-19/blob/master/notebooks/%5Bissue_36%5D_Tunar_par%C3%A2metros_com_dados_hist%C3%B3rico.ipynb).

**Comment by dsevero** [comment]
Coloquei nas referências do README! Obrigado
