### ISSUE TITLE
Branch permissions

### ISSUE THREAD

**Issue by hsteinshiromoto** [3778/COVID-19#42]
Caros,

Estive tentando criar um `dev` e `feature` branch no repositório para organizarmos a colaboração usando o git flow como padrão. Contudo, não tenho permissão para "pushar" estes branches. Será que os admins poderiam:

1. Autorizar a criação e push de feature branches?
2. Restringir o master como Pull / Merge request only?
3. Criar um dev. branch?

Abraços (sem o risco de corona)

**Comment by muriloazevedo** [comment]
@hsteinshiromoto ao invés de criar branches no repositório, não seria melhor seguir a técnico de fazer fork e depois PR? Assim permite colaboração de fora e o gerenciamento mais de perto dos administradores.

**Comment by hsteinshiromoto** [comment]
A vantagem de usar branches é ter certeza de ter o `master`e o `dev` sempre atualizados ;)

**Comment by dsevero** [comment]
Obrigado pela contribuição!

Meu entendimento é de que quando o projeto é interno de uma organização, liberar branch com gitflow é melhor. Mas em OS, fork costuma ser padrão por questão de organização (muita gente criando branch pode ser problemático).

Vocês podem criar um fork e uma PR?
