### ISSUE TITLE
App em produção dá "rerun" automático indevido a cada ~10s

### ISSUE THREAD

**Issue by luipillmann** [3778/COVID-19#49]
Ao testar o app em produção (https://covid-simulator.3778.care/), notei que a cada ~10 s é disparado um evento que executa novamente o Streamlit (como se fosse "rerun") sem ter sido solicitado. A resposta é como se tivesse sido feita alguma alteração nos parâmetros, mas sem ter sido clicado em nada. Aparece "Connecting..." e depois "Running..." no canto direito superior.

Isso é um problema pq os parâmetros são resetados e o fluxo de interação do usuário é interrompido, sem que se consiga finalizar um configuração e analisar os resultados minimamente.

Isso não acontece rodando localmente com `make launch`, então imagino que seja algo relacionado com a forma que fizemos o deploy.  Algum insight do que poderia ser @thiagocaiubi?

Cheguei a gravar um screencast pra ilustrar, mas por limitações técnicas (aka noob) não consegui subir aqui como GIF. Tô usando Firefox 74.0 (64-bit) no mac osx 10.15.3, mas acontece no Chrome 80.0.3987.149 também.

**Comment by thiagocaiubi** [comment]
Oi @luipillmann obrigado pelo reporte.

Normalmente o reinício de sessão no streamlit acontece quando há interrupção da conexão do websocket. Este cenário pode acontecer quando existe load balancer/proxy na frente do streamlit forçando um tempo curto de conexão. Este comentário no fórum do streamlit descreve algo similar: https://discuss.streamlit.io/t/crosstalk-between-streamlit-sessions-with-multiple-users/319/14.

Nós realizamos as devidas configurações afim de garantir mais tempo de conexão webscoket.
Você pode validar, por favor?

**Comment by luipillmann** [comment]
Agora tá OK, @thiagocaiubi!
