### ISSUE TITLE
Dados por município e/ou cidade (algo mais granular que estado).

### ISSUE THREAD

**Issue by dsevero** [3778/COVID-19#52]
A ideia é compilar fontes de dados, cuja ingestão seja automatizável, pra colocar no simulador.

Informações necessárias:
- numero de infectados
- recuperados
- mortes

População já temos vindo do IBGE

**Comment by dsevero** [comment]
Possíveis fontes: https://brasil.io/dataset/covid19/boletim

**Comment by dsevero** [comment]
O heroi que precisamos: https://raw.githubusercontent.com/wcota/covid19br/master/cases-brazil-cities-time.csv

**Comment by renatocmaciel** [comment]
Aonde ele conseguiu esses dados? Sabe se é atualizado diariamente?

**Comment by dsevero** [comment]
> Aonde ele conseguiu esses dados? Sabe se é atualizado diariamente?

Parece ser manualmente (veja os commits do repositório). Acho que é compilado das notícias, pelo que li.

Acho que vale retirar o checkbox de "usar populacao da capital" e deixar 2 seletores: Estado e Municipio/cidade, sendo que o primeiro define as opções do segundo. E dai carregar o dado de população, infectados, expostos (=infectados) e recuperados (note que agora da pra inferir, visto que tem a quantidade total de casos novos por dia.)

**Comment by tiagoyuzo** [comment]
> O heroi que precisamos: https://raw.githubusercontent.com/wcota/covid19br/master/cases-brazil-cities-time.csv
> 
> @renatocmaciel esse cara fez o trabalho que o governo não fez, **tem os casos novos por dia**

Esses dados vêm desse site: https://labs.wesleycota.com/sarscov2/br/

Tem tanto por estado quanto por município. As fontes estão detalhadas lá.

**Comment by tiagoyuzo** [comment]
> > Aonde ele conseguiu esses dados? Sabe se é atualizado diariamente?
> 
> Parece ser manualmente (veja os commits do repositório). Acho que é compilado das notícias, pelo que li.
> 
> Acho que vale retirar o checkbox de "usar populacao da capital" e deixar 3 seletores: Estado e Municipio/cidade (sendo que o primeiro define as opções do segundo) e data. E dai carregar o dado de população, infectados, expostos (=infectados) e recuperados (note que agora da pra inferir, visto que tem a quantidade total de casos novos por dia.)

É interessante ter os dados na granularidade de municípios, mas no caso de metrópoles, é ruim limitar a uma só cidade, porque a região metropolitana toda está de certa forma conectada. Isso pode causar distorções nas análises.

**Comment by dsevero** [comment]
> É interessante ter os dados na granularidade de municípios, mas no caso de metrópoles, é ruim limitar a uma só cidade, porque a região metropolitana toda está de certa forma conectada. Isso pode causar distorções nas análises.

Acho que depende do objetivo. No momento, estamos terminando a previsão de demanda de leitos e UTIs por município, logo a informação local é mais importante. Porém, concordo com você, que as regiões metropolitanas são hubs de infecção. Pra modelar melhor, teria que levar isso em consideração essa conectividade (talvez nos próximos dias dê pra fazer isso).
