### ISSUE TITLE
Botão de exportação dos dados da simulação

### ISSUE THREAD

**Issue by luipillmann** [3778/COVID-19#74]
Atualmente oferecemos somente a visualização, mas seria muito útil poder exportar os dados que estão plotados em formato CSV para uso em outros locais como continuação da análise.

Exportar:

- Dados do gráfico
- Parâmetros da simulação

**Comment by dsevero** [comment]
boa, vou adicionar os parâmetros tb, mas os dados em CSV já estão lá pra baixar
